### ISSUE TITLE
classify by kmers - short read.

### ISSUE THREAD

**Issue by leorippel** [esrice/trio_binning#6]
Hi. The classify_by_kmer script only works for Long Reads? The example is using long reads but I'm not sure if is just a use case. 

Thanks.

**Comment by esrice** [comment]
This is really designed for long reads, because short reads are too short to have a high probability of having a k-mer that distinguishes the two parents. You can still use it, though; it just won't work as well.

**Comment by leorippel** [comment]
thanks for the help.

I'm having a issue when I try to find Parental unique kmers:

```
./find-unique-kmers -k 21 -p 12 \
/input/genomic/plant/Actinidia/PopulationsStudies/ExperimentRequest10828/LF_000_0AB_004/SMRTcell1/CCS_Data/m64043_210804_173320.hifi_reads.fastq.gz \
/input/genomic/plant/Actinidia/PopulationsStudies/ExperimentRequest10828/LF_000_0AB_003/SMRTcell1/CCS_Data/m64043_210811_174115.hifi_reads.fastq.gz


Counting k-mers in haplotype A...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Traceback (most recent call last):
  File "./find-unique-kmers", line 242, in <module>
    main()
  File "./find-unique-kmers", line 199, in main
    args.threads, args.path_to_kmc, args.scratch_dir)
  File "./find-unique-kmers", line 71, in run_kmc
    check_call(kmc_cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['kmc', '-k21', '-t12', '@./1982267', './haplotypeA', '.']' died with <Signals.SIGABRT: 6>.

```
Do you now what's going on?

The input is PacBio (Parents) HiFi data.


Cheers

**Comment by esrice** [comment]
This looks like a problem in kmc. Not sure what it is. Maybe try running with more memory?
